### ISSUE TITLE
Dashatar version does not work

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [VGVentures/slide_puzzle#1]
**Description**

When clicking on the "Dashatar" button (next to the "Simple"), the whole app turns green and nothing else happens.

**Steps To Reproduce**

1. Go to https://very-good-puzzle.web.app/#/
2. Click on "Dashatar"

**Screenshots**

<img width="1673" alt="Screen Shot 2022-01-07 at 03 14 33" src="https://user-images.githubusercontent.com/19204050/148485627-c4d6236a-b49f-4211-8824-8a3fbfadc846.png">

**Comment by bselwe** [comment]
Hey @creativecreatorormaybenot, this URL is outdated, please use the one from [the Flutter Puzzle Hack resources](https://flutterhack.devpost.com/resources). You can visit it directly [here](https://flutter.github.io/samples/web/slide_puzzle/#/).

**Comment by creativecreatorormaybenot** [comment]
@bselwe This was the one from the Flutter Puzzle Hack resources back when I encountered the issue. But I see that you corrected it, thanks.
