### ISSUE TITLE
build:  No MainActivity Present for Android builds

### ISSUE THREAD

**Issue by kunalmanocha98** [VGVentures/slide_puzzle#3]
Add MainActivity for the android builds

**Comment by evkalinin** [comment]
https://github.com/VeryGoodOpenSource/very_good_cli/issues/196#issuecomment-931435287

verygoodcore lowercase

**Comment by renefloor** [comment]
It is indeed fixed when you add the following file:

android/app/src/main/kotlin/com/example/verygoodcore/MainActivity.kt

```kotlin
package com.example.verygoodcore

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {

}
```

**Comment by SofieTorch** [comment]
It's fixed now! in the last version of release the MainActivity.kt file was implemented :)

**Comment by bselwe** [comment]
Thanks all for the contribution! It's now solved in https://github.com/VGVentures/slide_puzzle/pull/6.
