### ISSUE TITLE
fix: 

### ISSUE THREAD

**Issue by Abdallah-al-hallak** [VGVentures/slide_puzzle#7]
The Localization doesn't wor
![bug](https://user-images.githubusercontent.com/57962596/150527885-fb2f00bb-e629-49bf-8077-2d88979b0176.PNG)
![bug2](https://user-images.githubusercontent.com/57962596/150527892-e3f454cc-f9b2-46b9-ae33-ab974145a624.PNG)
k

**Comment by orestesgaolin** [comment]
Please have a look at this issue and solution https://github.com/Dart-Code/Dart-Code/issues/3438#issuecomment-981489426
